import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { DimensionalAnalysis } from '@/components/dimension-a'
import { MultiStepDimensionalAnalysis } from '@/components/dimension-multi'


export default function Home() {
  return (
    <>
      <Head>
        <title>Dimensional Analysis | Siddharth Duggal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
    </>
  )
}
